### ISSUE TITLE
LIDAR Lite and RPi

### ISSUE THREAD

**Issue by assemmarwan** [PulsedLight3D/LIDARLite_Basics#4]
I am using the RPi to sense the distance usnig the LIDAR Lite. Is there a need for a level shifter between the LIDAR and the RPi since the LIDAR outputs 5V?

**Comment by ak5a** [comment]
Hey there, I'm going to forward this to our engineer and get his feedback. As far as I know you wouldn't need a level shifter... I believe the i2c communications are 3.3v... but let me check to be absolutely sure.

**Comment by assemmarwan** [comment]
Hello,

Thanks for the response, but I have tried it with RPi without any level shifter and it works fine.

Thanks again!
