### ISSUE TITLE
Wrong I2C addresses

### ISSUE THREAD

**Issue by gbrivet** [PulsedLight3D/LIDARLite_Basics#5]
In the file: LIDARLite_Basics/TI_Tiva_C_Series/main.c

I2C addresses look inverted, Write should be 0xC4 and Read should be 0xC5

**Comment by ak5a** [comment]
If this works right for you, I'm happy to change it... this was code donated by one of our users. So just let me know and I'll fix it up!

**Comment by gbrivet** [comment]
I haven't tested it, just looking at it as a reference. However, code can't be right...

**Comment by ak5a** [comment]
Thanks for catching that, I haven't tested it either, but I agree!
