### ISSUE TITLE
Get Distance 12C vs PWM Issue

### ISSUE THREAD

**Issue by Vinterwoo** [PulsedLight3D/LIDARLite_Basics#7]
I am running a LidarLite (Blue Label) on an Arduino Uno board, wired up exactly as pictured in the diagrams on this site (minus the capacitor). 

I used the PWM GetDistance code located on this site with no issues. But when I use the I2C version (wired appropriately), all I get is a series of zeroes. The sensor is brand new and works with the PWM set up, so I don't think it's a sensor problem. And the wiring is pretty simple so I'm confident I have it wired up correctly. I am plugging in the unaltered code from this site directly into the Arduino IDE (Mac), so I'm wondering if there is something I need to do with the code to make it work correctly. Is there any reason I should be getting a string of zeros as opposed to the distance data?

**Comment by nprestel** [comment]
I'm running into this same issue exactly as described above. My LidarLite (blue label) works fine using the LIDARLite_Wire_Library_GetDistance_ContinuousRead sketch but i2C returns nothing but zeroes.

**Comment by ak5a** [comment]
One important note... this library only works with LIDAR-Lite v1 (silver label). The I2C master library by DSS circuits was written specifically to do repeated starts during I2C reads and unfortunately is not compatible with LIDAR-Lite v2 (blue label) which requires a stop then a start during reads. So sorry for any confusion.
